### ISSUE TITLE
Translucency support

### ISSUE THREAD

**Issue by drothlis** [stb-tester/stb-tester#216]
Dependencies:
- [x] stbt.match (pull request #182)
- [x] stbt.match_all (pull request #212)

Transparency support (`stbt.match` ignores transparent pixels in the reference image):
- [x] #542.

Translucency support (match things on a translucent overlay, ignoring the background content that shows through):
- [ ] Try thresholding frame & template images to eliminate background  #432 
- [ ] Try implementing our own first pass: Scoring algorithm gives different weight to each pixel based on alpha
  - [ ] Figure out weighting
  - [ ] Figure out the best colour space to do this in
- [ ] Try SSIM as second pass
- [ ] ???

**Comment by drothlis** [comment]
Note that OpenCV 3.x's matchTemplate supports a mask for the template ([docs](http://docs.opencv.org/3.1.0/df/dfb/group__imgproc__object.html#ga586ebfb0a7fb604b35a23d85391329be)).

OpenCV 3 seems to include breaking API changes. They've dropped the C API but it still has Python bindings ("greatly improved" Python bindings according to the [3.0 release notes](http://opencv.org/opencv-3-0.html)).

3.0 was released in June 2015 but it still hasn't made its way into any Ubuntu release (14.04 has 2.4.8, 16.04 has 2.4.9). Fedora rawhide (25) currently has opencv 3.1.0. The latest Fedora release (24) has 2.4.12.

**Comment by drothlis** [comment]
Ubuntu 18.04 has OpenCV 3 so we'll use its `mask` support for transparency in the reference image: #542.

**Comment by drothlis** [comment]
Transparency support (i.e. ignore transparent pixels in the reference image) was released in v30. I've renamed this issue to "Translucency support".

**Comment by wmanley** [comment]
We don't have any imminent plans to work on this so I'll close for now.  The most important part was already merged in #542.  We can re-open in the future if that changes.
