### ISSUE TITLE
Librification

### ISSUE THREAD

**Issue by wmanley** [stb-tester/stb-tester#297]
It would be good if stbt could be used as a well behaved library, rather than requiring `stbt run` to be used if you want to use the library.  This would aid integration with other testing frameworks such as py.test.

By well-behaved I mean:
1. Has no global state
2. Can be cleanly initialised and completely deinitialised
3. Configuration can be injected rather than is loaded from disk implicitly

TODO (probably incomplete):
- [x] Create a `DeviceUnderTest` class refactoring global variables into it #285 
- [x] Refactor `Display` to separate the sink-pipeline into a seperate class, allowing the sink-pipeline and the `DeviceUnderTest` objects to have independent lifetimes #420 
  - This would be needed for py.test support as I would think the `DeviceUnderTest` class would be a (potentially long-lived) pytest fixture, but the output video would probably be implemented using some kind of [runtest hook](https://pytest.org/latest/plugins.html#generic-runtest-hooks)
- [ ] Inject all configuration into the `DeviceUnderTest` class, removing any calls to `get_config` outside of a factory function? #333
- [x] Remove `stbt.init_run` and `stbt.teardown_run`.
  - `DeviceUnderTest` is already a `contextmanager`.
- [x] Create a `contextmanager` or similar to take care of most of the concerns of `stbt run` and refactor `stbt run` to use it.

**Comment by allanlewis** [comment]
Thanks @wmanley  - this will be useful for tracking progress towards librarification (is that a word?) of `stb-tester` :+1:

**Comment by drothlis** [comment]
@martynjarvis @LewisHaley @jcutbush @johnteslade @allanlewis have you guys done any work on the above?

**Comment by LewisHaley** [comment]
None at all.

**Comment by wmanley** [comment]
I'm not planning on doing any more work on this for the time being, closing.

**Comment by drothlis** [comment]
It's pretty much done already, at least for the use case of being able to `import stbt` for linting, IDEs, etc.
