### ISSUE TITLE
adb (android) control

### ISSUE THREAD

**Issue by drothlis** [stb-tester/stb-tester#386]
### TODO

- [x] `stbt.android.AdbDevice` with `press`, `tap`, and `swipe` methods. #417 
- [x] Add `stbt run --control` configuration to use `stbt.android.AdbDevice.press` from `stbt.press`. #491
    - [x] Provide a mapping for our default key names to the Android [KEYCODE_xxx codes](https://developer.android.com/reference/android/view/KeyEvent.html)?

---

Useful for:
- Android phones & tablets.
- Android TVs?
- Amazon Fire.

This is a placeholder issue to jot down some notes.
### adb input API

```
$ adb shell input -help
Error: Unknown command: -help
Usage: input [<source>] <command> [<arg>...]

The sources are: 
      trackball
      joystick
      touchnavigation
      mouse
      keyboard
      gamepad
      touchpad
      dpad
      stylus
      touchscreen

The commands and default sources are:
      text <string> (Default: touchscreen)
      keyevent [--longpress] <key code number or name> ... (Default: keyboard)
      tap <x> <y> (Default: touchscreen)
      swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      press (Default: trackball)
      roll <dx> <dy> (Default: trackball)
```

You can do a tap-and-hold by doing a swipe with the same x & y coordinates:
`input swipe 420 170 420 170 2000`
### Appium API

https://github.com/appium/python-client

```
>>> from appium import webdriver
>>> driver = webdriver.Remote(...)
>>> driver.tap?
Signature: driver.tap(positions, duration=None)
Docstring:
Taps on an particular place with up to five fingers, holding for a
certain time

:Args:
 - positions - an array of tuples representing the x/y coordinates of
 the fingers to tap. Length can be up to five.
 - duration - (optional) length of time to tap, in ms

:Usage:
    driver.tap([(100, 20), (100, 60), (100, 100)], 500)
File:      ~/.local/lib/python2.7/site-packages/appium/webdriver/webdriver.py
Type:      instancemethod

>>> driver.swipe?
Signature: driver.swipe(start_x, start_y, end_x, end_y, duration=None)
Docstring:
Swipe from one point to another point, for an optional duration.

:Args:
 - start_x - x-coordinate at which to start
 - start_y - y-coordinate at which to start
 - end_x - x-coordinate at which to stop
 - end_y - y-coordinate at which to stop
 - duration - (optional) time to take the swipe, in ms.

:Usage:
    driver.swipe(100, 100, 100, 400)
File:      ~/.local/lib/python2.7/site-packages/appium/webdriver/webdriver.py
Type:      instancemethod
```

**Comment by drothlis** [comment]
Implemented in #491.
