### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by drothlis** [stb-tester/stb-tester#595]
Allow running Python 2 or 3 test scripts from the same stb-tester codebase.

- [x] Use Python 3 future imports (print function, unicode literals, etc) and backported builtins everywhere. Get pylint passing on both 2 & 3. #583 
- [x] Get unit tests passing on Python 3. #594 
- [x] Get integration tests passing on Python 3 (`make check-integrationtests` -- this tests integration with GStreamer, via the `stbt run` command-line interface; but it doesn't test against real video-capture or lirc hardware). #597
- [x] Test `stbt.press()` with real LIRC. #597
- [x] Python 3: stbt run: Any python files in pwd are imported. Fixed in #594 commit 02dcdd0 "Python3: Don't import from future.moves (again)".
    - This is also the cause of bug: Python 3: `print` output is duplicated.
- [x] Packaging: be able to build separate Python2 & Python3 debian packages. #598 
    -  As far as I can tell, you set the shebang to /usr/bin/python in your sources (already done in #583), and `setuptools` ~~modifies the shebang line when it installs the files~~ installs a wrapper script with the appropriate shebang. We don't use setuptools because we have so many non-python dependencies but it seems to be the (a?) standard [[1]](https://packaging.python.org/guides/tool-recommendations/#packaging-tool-recommendations).

Post-merge todo items from #583:

- [x] Revisit pylint:disable=stop-iteration-return ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283794786), [comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283798358)) #593 #594.
- [ ] Revisit raise AdbError as bytes ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283804013))
- [ ] Revisit android._adb return type ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283805392))
- [x] Check if `struct.pack` first argument has to be bytes ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283822226))
- [ ] Avoid decoding + re-encoding byte-string tesseract_user_words & patterns ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283823127))
- [ ] Should subprocess arguments be bytes? ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283827316))
- [x] Change regexes to bytes in stbt_lint.py ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283828269))
- [x] Do to_bytes later in videotestsrccontrol.press ([comment](https://github.com/stb-tester/stb-tester/pull/583#discussion_r283835162))

**Comment by drothlis** [comment]
Hmmm [six] has more recent releases than python-future. I wonder why I thought the latter was the replacement for six? Oh well it's done now.

[six]: https://pypi.org/project/six/

**Comment by drothlis** [comment]
@wmanley how important do you think the remaining todo items (above) are?

**Comment by wmanley** [comment]
I don't think any of them are particularly important.  But equally they don't seem like they're big tasks.

**Comment by drothlis** [comment]
This has been well tested with several customer test-packs using v31 Beta.
